#!/usr/bin/env python3
"""Write the generated smoke-test images used to prove the pipeline runs.

Run by ``scripts/setup.py`` through the virtualenv interpreter, because it
needs numpy and Pillow. It is a separate file for that reason: setup.py itself
must import nothing outside the standard library, since it runs on the system
Python before any dependency exists.

    python scripts/make_smoke_images.py [OUTPUT_DIR]

The images are a colour gradient and a field of random noise. They are NOT
photographs and NOT AI-generated pictures, so the probabilities the detector
assigns them are not detection results and say nothing about its accuracy.
They exist so the CLI has something to read on a machine with no dataset
downloaded.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DIR = PROJECT_ROOT / "data/smoke_sample"

README = """# Smoke-test images

Generated by `scripts/setup.py`, not shipped in the repository and not part of
any dataset.

They are a colour gradient and a field of random noise. They exist so that
`scripts/run_inference.py` has something to read on a fresh machine, and they
prove the pipeline runs end to end: validation, transformation, batching and
JSON output.

**Their scores are not detection results.** Neither image is a photograph or an
AI-generated picture, so whatever probability the model assigns to them says
nothing about the detector's accuracy. Use your own images, or the evaluation
dataset (`python3 scripts/setup.py --dataset`), to judge that.
"""


def write_smoke_images(output_dir: Path = DEFAULT_DIR) -> list[Path]:
    """Write the images and their README, returning the image paths."""

    output_dir.mkdir(parents=True, exist_ok=True)

    y, x = np.mgrid[0:256, 0:256]
    gradient = np.stack([x, y, (x + y) // 2], axis=-1).astype(np.uint8)
    Image.fromarray(gradient).save(output_dir / "gradient.png")

    # Seeded, so re-running setup does not silently change the inputs a
    # reported smoke-test result was produced from.
    rng = np.random.default_rng(1234)
    noise = rng.integers(0, 256, (256, 256, 3), dtype=np.uint8)
    Image.fromarray(noise).save(output_dir / "noise.png")

    (output_dir / "README.md").write_text(README, encoding="utf-8")
    return [output_dir / "gradient.png", output_dir / "noise.png"]


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DIR
    written = write_smoke_images(target)
    print(f"  wrote {len(written)} smoke-test images to {target}")


if __name__ == "__main__":
    main()
